default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("API_PG_USER") { "postgres" } %>
  password: <%= ENV.fetch("API_PG_PASS") { "" } %>
  host: <%= ENV.fetch("API_PG_HOST") { "localhost" } %>

development:
  <<: *default
  database: ddd_rails_example_development

test:
  <<: *default
  database: ddd_rails_example_test

production:
  <<: *default
  database: ddd_rails_example_production
